version: "3"

services:
  drupalvm:
    image: geerlingguy/drupal-vm
    container_name: ddkits_docker
    ports:
      - 80:80
      - 443:443
    privileged: true
    volumes:
      - ./:/var/www/drupalvm/drupal/:rw,delegated
      - /var/lib/mysql
    command: /lib/systemd/systemd
